  /api/Hizlisatisbutonayarlari/getall:
    post:
      requestBody:
        content:
          application/*+json:
            schema:
              $ref: '#/components/schemas/HizlisatisbutonayarlariFilterHelper'
          application/json:
            schema:
              $ref: '#/components/schemas/HizlisatisbutonayarlariFilterHelper'
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/HizlisatisbutonayarlariFilterHelper'
          text/json:
            schema:
              $ref: '#/components/schemas/HizlisatisbutonayarlariFilterHelper'
      responses:
        '200':
          description: Success
      summary: Hızlı Satış Buton Ayarlarını Listele
      description: >-
        Sistemdeki tüm hızlı satış buton ayarlarını getirir. Bu işlem, hızlı satış
        buton ayarlarının listelenmesi ve gözden geçirilmesi için kullanılır.
      tags:
        - Hızlı Satış Buton Ayarları
  /api/Hizlisatisbutonayarlari/getbyid:
    get:
      parameters:
        - explode: true
          in: query
          name: id
          required: false
          schema:
            format: int32
            type: integer
          style: form
      responses:
        '200':
          description: Success
      summary: Hızlı Satış Buton Ayar Listele ID ile
      description: >-
        Belirtilen ID'ye sahip hızlı satış buton ayarını getirir. Bu işlem,
        belirli bir hızlı satış buton ayarının detaylarını görüntülemek için
        kullanılır.
      tags:
        - Hızlı Satış Buton Ayarları
  /api/Hizlisatisbutonayarlari/add:
    post:
      requestBody:
        content:
          application/*+json:
            schema:
              $ref: '#/components/schemas/Hizlisatisbutonayarlari'
          application/json:
            schema:
              $ref: '#/components/schemas/Hizlisatisbutonayarlari'
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Hizlisatisbutonayarlari'
          text/json:
            schema:
              $ref: '#/components/schemas/Hizlisatisbutonayarlari'
      responses:
        '200':
          description: Success
      summary: Hızlı Satış Buton Ayar Ekle
      description: >-
        Yeni bir hızlı satış buton ayarı kaydı ekler. Bu işlem, hızlı satış
        işlemlerinde kullanılacak buton ayarlarının sisteme eklenmesini sağlar.
      tags:
        - Hızlı Satış Buton Ayarları
  /api/Hizlisatisbutonayarlari/addrange:
    post:
      requestBody:
        content:
          application/*+json:
            schema:
              items:
                $ref: '#/components/schemas/Hizlisatisbutonayarlari'
              type: array
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/Hizlisatisbutonayarlari'
              type: array
          application/json-patch+json:
            schema:
              items:
                $ref: '#/components/schemas/Hizlisatisbutonayarlari'
              type: array
          text/json:
            schema:
              items:
                $ref: '#/components/schemas/Hizlisatisbutonayarlari'
              type: array
      responses:
        '200':
          description: Success
      summary: Hızlı Satış Buton Ayar Ekle Toplu
      description: >-
        Birden fazla hızlı satış buton ayarını toplu olarak sisteme ekler. Bu
        işlem, çok sayıda hızlı satış buton ayarının aynı anda eklenmesini sağlar.
      tags:
        - Hızlı Satış Buton Ayarları
  /api/Hizlisatisbutonayarlari/update:
    put:
      requestBody:
        content:
          application/*+json:
            schema:
              $ref: '#/components/schemas/Hizlisatisbutonayarlari'
          application/json:
            schema:
              $ref: '#/components/schemas/Hizlisatisbutonayarlari'
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Hizlisatisbutonayarlari'
          text/json:
            schema:
              $ref: '#/components/schemas/Hizlisatisbutonayarlari'
      responses:
        '200':
          description: Success
      summary: Hızlı Satış Buton Ayar Güncelle
      description: >-
        Belirtilen ID'ye sahip hızlı satış buton ayarını günceller. Bu işlem,
        mevcut hızlı satış buton ayarlarının bilgilerini güncellemek için
        kullanılır.
      tags:
        - Hızlı Satış Buton Ayarları
  /api/Hizlisatisbutonayarlari/updaterange:
    put:
      requestBody:
        content:
          application/*+json:
            schema:
              items:
                $ref: '#/components/schemas/Hizlisatisbutonayarlari'
              type: array
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/Hizlisatisbutonayarlari'
              type: array
          application/json-patch+json:
            schema:
              items:
                $ref: '#/components/schemas/Hizlisatisbutonayarlari'
              type: array
          text/json:
            schema:
              items:
                $ref: '#/components/schemas/Hizlisatisbutonayarlari'
              type: array
      responses:
        '200':
          description: Success
      summary: Hızlı Satış Buton Ayar Güncelle Toplu
      description: >-
        Belirtilen aralıkta bulunan hızlı satış buton ayarlarını toplu olarak
        günceller. Bu işlem, birden fazla hızlı satış buton ayarının aynı anda
        güncellenmesi gerektiğinde kullanılır.
      tags:
        - Hızlı Satış Buton Ayarları
  /api/Hizlisatisbutonayarlari/delete:
    post:
      requestBody:
        content:
          application/*+json:
            schema:
              $ref: '#/components/schemas/Hizlisatisbutonayarlari'
          application/json:
            schema:
              $ref: '#/components/schemas/Hizlisatisbutonayarlari'
          application/json-patch+json:
            schema:
              $ref: '#/components/schemas/Hizlisatisbutonayarlari'
          text/json:
            schema:
              $ref: '#/components/schemas/Hizlisatisbutonayarlari'
      responses:
        '200':
          description: Success
      summary: Hızlı Satış Buton Ayar Sil
      description: >-
        Belirtilen hızlı satış buton ayarını sistemden siler. Bu işlem, mevcut bir
        hızlı satış buton ayarının kaldırılmasını sağlar.
      tags:
        - Hızlı Satış Buton Ayarları
  /api/Hizlisatisbutonayarlari/deletebyid:
    delete:
      parameters:
        - explode: true
          in: query
          name: entityId
          required: false
          schema:
            format: int32
            type: integer
          style: form
      responses:
        '200':
          description: Success
      summary: Hızlı Satış Buton Ayar Sil ID ile
      description: >-
        Belirtilen ID'ye sahip hızlı satış buton ayarını sistemden siler. Bu
        işlem, belirli bir hızlı satış buton ayarının kaldırılmasını sağlar.
      tags:
        - Hızlı Satış Buton Ayarları
  /api/Hizlisatisbutonayarlari/deleterange:
    post:
      requestBody:
        content:
          application/*+json:
            schema:
              items:
                $ref: '#/components/schemas/Hizlisatisbutonayarlari'
              type: array
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/Hizlisatisbutonayarlari'
              type: array
          application/json-patch+json:
            schema:
              items:
                $ref: '#/components/schemas/Hizlisatisbutonayarlari'
              type: array
          text/json:
            schema:
              items:
                $ref: '#/components/schemas/Hizlisatisbutonayarlari'
              type: array
      responses:
        '200':
          description: Success
      summary: Hızlı Satış Buton Ayar Sil Toplu
      description: >-
        Belirtilen aralıkta bulunan hızlı satış buton ayarlarını toplu olarak
        siler. Bu işlem, birden fazla hızlı satış buton ayarının aynı anda
        kaldırılması gerektiğinde kullanılır.
      tags:
        - Hızlı Satış Buton Ayarları
